### ISSUE TITLE
Add Box Plot Helper

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#13]
## Background
According to Newcastle University...

> A box and whisker plot or diagram (otherwise known as a boxplot), is a graph summarising a set of data. The shape of the boxplot shows how the data is distributed and it also shows any outliers. It is a useful way to compare different sets of data as you can draw more than one boxplot per graph ([source](https://www.ncl.ac.uk/webtemplate/ask-assets/external/maths-resources/statistics/data-presentation/box-and-whisker-plots.html)).

![image](https://github.com/PureChart/purechart/assets/43429820/4a928c2a-8ac4-4828-a6cd-291535ac31b7)

We would like to provide users with a box plot helper!

## Goal
Add a helper called `box_plot` to `lib/purechart/chart_helper.rb` that takes a set of data points and axis labels. It should render an SVG box plot. Here are a few shortcuts you can make to keep things simple for now - we'll add them later.
- For the time being, your helper only needs to handle _one_ set of data. In the future, it should be able to display several data sets on the same axis
- Don't worry about rendering a fancy axis with labels or titles yet - just the box and whisker plot will do
  - You might want to add axes anyways to confirm your chart is rendered correctly - for this I would suggest using HTML with inline styles and overlaying the SVG chart over the HTML/CSS axes using [absolute positioning](https://www.w3schools.com/css/css_positioning.asp))
- Custom styling will be addressed in a separate issue - for now, just use hardcoded colors

You can style the box plot in any way you'd like! However, please render it _horizontally_ for now. Another issue will add options for horizontal versus vertical positioning in the future.

**Comment by ethanwithnoe** [comment]
I can work on this one!

**Comment by raj978** [comment]
Hey, I’ll give this one a try too!

**Comment by skyz04** [comment]
i'll take a stab at this

**Comment by GeorgeBerdovskiy** [comment]
Hey @skyz04, I actually just merged @ethanwithnoe's PR for this. I'm about to open several new issues regarding the box plot though and will ping you here when I do 😁

**Comment by GeorgeBerdovskiy** [comment]
@skyz04 check out #25 and #26 if interested!
