### ISSUE TITLE
Add Line Plot Helper

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#14]
## Background
A line plot consists of a horizontal or vertical line with ticks for categories and points stacked over each tick to indicate the count of that category (not a very formal description, but hopefully it gets the point across 😉). It should look something like this...

![image](https://github.com/PureChart/purechart/assets/43429820/e6566f47-2bba-4f04-ba3a-daf3393ac7e2)

We would like to provide users with a line plot helper!

## Goal
Add a helper called `line_plot` to `lib/purechart/chart_helper.rb` that takes a set of data points (and optionally a set of categories - the alternative is to build the categories from the data set). It should render a _horizontal_ SVG line plot (the option for rendering it vertically will be addressed in a separate issue).

To keep things simple, just use black and white - no need for custom styling yet! That will also be addressed in a separate issue.

Good luck 🚀

**Comment by matthewh8** [comment]
I can do this!

**Comment by skyz04** [comment]
ill take this one

**Comment by raj978** [comment]
Hey, I’ll give this one a try too!

**Comment by GeorgeBerdovskiy** [comment]
Go ahead @raj978! I'll merge whichever PR is opened first 🙂

**Comment by GeorgeBerdovskiy** [comment]
Closed by #27!
