### ISSUE TITLE
Add Bar Chart Helper

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#16]
## Background
According to [Wikipedia](https://en.wikipedia.org/wiki/Bar_chart), a "bar chart or bar graph is a chart or graph that presents categorical data with rectangular bars with heights or lengths proportional to the values that they represent." You've probably seen one before - they are very common. Here's an example just in case you're unfamiliar -

![image](https://github.com/PureChart/purechart/assets/43429820/949011f7-f7f4-4e62-99c4-48a8c7d54eab)

Like pie charts (#13), bar charts are also commonplace on analytics dashboards, so we'd like to implement them as soon as possible!

## Goal
Modify the existing `bar_chart` helper in `lib/purechart/chart_helper.rb` so that it takes a set of data points and axis labels, which it uses to render an HTML/CSS bar plot.

You might be wondering, _why is this issue labeled "beginner"?_ And also, _why aren't we rendering it as an SVG?_ That's because we've already implemented a similar chart using HTML/CSS - the **lollipop chart!**

For that reason, I recommend copying and pasting almost all of the code for the lollipop chart (including the helper logic, with variable names changed as necessary) and simply modifying the template to get rid of the circles at the end of each bar and making the bars thicker.

**Comment by matthewh8** [comment]
i can do this!

**Comment by GeorgeBerdovskiy** [comment]
Closed by #18
