### ISSUE TITLE
Begin Line Graph Helper

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#19]
## Background
One of the **most important** graphs PureChart will provide is the line graph. This is _not_ the same thing as a line plot (#14)! It's really a dot plot but with lines in between the dots. Here are two examples of what that may look like -

![image](https://github.com/PureChart/purechart/assets/43429820/25cd283a-8688-4d4b-8b27-b7713bddcb72)

![image](https://github.com/PureChart/purechart/assets/43429820/f8dba9af-4940-488d-97fc-7edc9741b4bc)

## Goal
We want to provide users with a flexible line graph helper called `line_graph`! The method already exists in `lib/purechart/chart_helper.rb` and simply needs to be implemented.

#### Data
Assume the data will be structured like this (as an array of hashes) -
```rb
[
  {
    label: "Car One",
    color: "blue",
    data: [
      {
        x: 50,
        y: 50
      },
      {
        x: 100,
        y: 100 
      },
      ...
    ]
  },
  {
    label: "Car Two",
    color: "Green",
    data: [...]
  },
  ...
]
```

#### Configuration
Assume the configuration will be structured like this -
```rb
{
  show_dots: true,
  smooth: false,
  axes: {
    horizontal: "Time (s)",
    vertical: "Displacement (m)"
  }
}
```

## Notes
- You may need to use a combination of SVG and HTML/CSS
    - For example, you might render the dots / lines in SVG format and overlay it on a set of axes created using HTML/CSS
    - However, if you feel comfortable rendering the entire graph in one format or another, please do so!

**Comment by arnavakula** [comment]
I can try this one :)

**Comment by Agarwal-Sambhav** [comment]
I can try this one as well.
