### ISSUE TITLE
Create Dot Plot Helper Method

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#2]
## Background
**Helpers** in Ruby on Rails are methods you can use in your views. They are commonly used to perform common tasks or display data in a certain way [[🔗](https://reintech.io/blog/how-to-use-rails-helpers)]. As you may imagine, this means we can use helpers to generate charts!

## Goal
Create a new helper method called `dot_plot` in `lib/purechart/chart_helper.rb`. For now, it should just return some HTML that says "Dot plot will be generated here" - no graph generation is necessary yet! Please use the existing helper methods as a guide. Good luck!

**Comment by ReehalS** [comment]
Ill Work on this

**Comment by GeorgeBerdovskiy** [comment]
Closed by PR #10
