### ISSUE TITLE
Add Styling Support for Box Plots

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#25]
## Background
Thanks to #20, PureChart now supports box plots! However, they are always rendered using the same color scheme. We would like to provide users with the opportunity to choose a styling configuration or define their own (like we do for lollipop charts already).

<img width="1624" alt="image" src="https://github.com/PureChart/purechart/assets/43429820/d9b034d9-7cbe-402f-b90b-1c75ff794e61">

## Goal
Add an argument for style configuration to the `box_plot` helper method. Logic for styling configuration here should be almost identical to the logic for lollipop charts (future potential task - separate this logic into its own function for modularity). If the user specifies a configuration we have (example - `futuristic_light.yml`), then use it. If we don't have the specified configuration, it must live in the user's project. If no style configuration is specified, use the default one (`default.yml`).

Good luck 🙌

**Comment by viveknarayana** [comment]
I'll work on this

**Comment by GeorgeBerdovskiy** [comment]
Closed by #29
