### ISSUE TITLE
Add Pie Chart Support for Negative Values

### ISSUE THREAD

**Issue by yooian** [PureChart/purechart#30]
## Background
The pie chart takes in values from a given data set and converts them into percentages, which is used to render a slice on screen. 

However, the pie chart breaks when the user passes a data set with negative values. This is because the ```total_value``` calculation in ```chart_helper.rb``` assumes only positive numbers will be summed. A negative subtracts from the whole and alters the percentages for every other data point.

## Goal
When a negative data value is passed, it is usually due to user error. Therefore, we would like to alert the user to this (potential) mistake.

However, there are occasions when negative values are expected within a data set. Ideally, pie charts should not be used to represent data with negative values. However, this is up to the user, and we should attempt to accommodate this option with a special graphical representation!

### Expected Behavior
When negative values are passed in, we want:
1. Error message alerting the user of negative values in the data set
2. Special render of pie chart that accommodates negative values

Here is an example of what (2) could look like!
(Ignore that it is a donut chart)
![](https://i.stack.imgur.com/1qfZT.png)
### Actual Behavior
<img width="295" alt="image" src="https://github.com/PureChart/purechart/assets/146519652/3e5fda2e-0fa6-4b91-9093-98fe96dc82b3">

<img width="284" alt="Screenshot 2024-03-09 at 1 42 02 AM" src="https://github.com/PureChart/purechart/assets/146519652/9283fd43-b8af-412b-afd0-4d0614af22a7">

### Steps to Reproduce the Problem

1. Change any value in a data set to negative
2. Pass it to the pie chart

## Resources

This pie chart is rendered using svg ```<path>``` elements and other related properties. 
- How can we use these tools to render a blank slice?
- Is there a way to draw a pie shape with a dotted outline?
- How can we edit the code in ```_pie.html.erb``` to account for negative values when rendering pie slices?

Remember - when a pie chart with negative values is rendered, we still need the ```total_value``` to correctly reflect the full data set. Edit the code in ```chart_helper.rb``` to account for negative values!

**Comment by GeorgeBerdovskiy** [comment]
Reserving for @skyz04 since their issue was closed by another PR 🙂

**Comment by GeorgeBerdovskiy** [comment]
@skyz04 addressed this issue in #33 but without the error message. We can come back to that later 🙂
