### ISSUE TITLE
Add Axis to Dot Plot

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#36]
## Background
Due to PR #34, PureChart finally supports dot plots! However, they are too simple to be used practically. Since points are now being rendered successfully, the next step is to draw labeled x- and y-axes.

## Goal
Add axes to the dot plot using the image below for guidance. The method you'll be working on is `dot_plot` in `lib/purechart/chart_helper.rb`.

<img width="637" alt="image" src="https://github.com/PureChart/purechart/assets/43429820/f6c1343e-f7ff-44c7-ac68-7a2b7f156fcb">

You may use either HTML/CSS or SVG code to accomplish this. Make sure to check the way axes are rendered for lollipop charts before getting started - it may help. Good luck!

**Comment by GeorgeBerdovskiy** [comment]
**Notice that there are no x-axis ticks?** That's because line graphs currently take only the y-values and space them out horizontally. This will be changed in the future but don't worry about it until then. If it looks like the picture it's good 😉

**Comment by viveknarayana** [comment]
I can try this

**Comment by GeorgeBerdovskiy** [comment]
Closed by #40
