### ISSUE TITLE
Transfer SVG Dot Drawing Code to Dot Plot Helper

### ISSUE THREAD

**Issue by GeorgeBerdovskiy** [PureChart/purechart#5]
## Background
In issue #4, we created a helper that draws an SVG with some randomly scattered points, and in issue #2, we created a helper to generate dot (or scatter) plots.

Please combine that code into the `dot_plot` helper and remove the `dot_svg_render` helper! At the same time, modify the signature of `dot_plot` to take an argument for data and use the points inside that argument to draw the dots.

## Goal
Modify the `dot_plot` helper to take an argument with data, and use that data to draw the dots. Assume the data will be formatted like this -

```
[
  {
    name: "P1",
    x: 0,
    y: 0
  },
  {
    name: "P2",
    x: 50,
    y: 75
  },
  {
    name: "P3",
    x: 60,
    y: 80
  },
  ...
]
```

The resulting SVG code should be something like this...
```html
<svg width="100" height="100" xmlns="http://www.w3.org/2000/svg" style="border: 1px dashed lightgray;">
  <!-- P1 -->
  <circle cx="calc(0px + 3px)" cy="calc(100px - 0px - 3px)" r="3" fill="red" name="P1"/>
 
  <!-- P2 -->
  <circle cx="calc(50px + 3px)" cy="calc(100px - 75px - 3px)" r="3" fill="red"/>
  
  <!-- P3 -->
  <circle cx="calc(60px + 3px)" cy="calc(100px - 80px - 3px)" r="3" fill="red"/>
</svg>
 ```

... which should look something like this when rendered!
<img width="271" alt="image" src="https://github.com/PureChart/purechart/assets/43429820/bf5d4ddb-6690-4ca0-b169-9c0f22e80f99">

Check out [W3Schools](https://www.w3schools.com/graphics/tryit.asp?filename=trysvg_myfirst) for interactive SVG tutorials you can play around with in your web browser. Good luck!

**Comment by ReehalS** [comment]
I'll work on this

**Comment by sarayumummidi** [comment]
I can take a shot at this!

**Comment by GeorgeBerdovskiy** [comment]
@matthewh8 will be working on this one now!

**Comment by GeorgeBerdovskiy** [comment]
**Update -** I'm going to address this issue since the code has already been written.
